import type { Metadata } from "next";
import { Mulish, Anton } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart/CartContext";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ConditionalFooter from "@/components/layout/ConditionalFooter";
// Welcome screen removed
import ToastProvider from "@/components/ToastProvider";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-mulish",
});

const displayFont = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "furniture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${mulish.className} ${displayFont.variable} antialiased bg-[#FAFAFA] text-neutral-900`}
      >
        <CartProvider>
          <Navbar />
          <main className="min-h-screen">{children}</main>
          <ConditionalFooter />
          <ToastProvider />
        </CartProvider>
      </body>
    </html>
  );
}
